# Generated by Django 5.0.6 on 2024-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
