# Generated by Django 5.2.4 on 2025-08-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_credentials_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
    ]
